- debian/control
treeland-helper need qt6-wayland
> Add missking runtime depends

- src/treeland/Main.qml
- src/treeland/StackWorkspace.qml
https://github.com/vioken/waylib/issues/180
Depend: https://github.com/vioken/waylib/pull/214
> Support set different DecorationMode for which xdg surface

- src/treeland/StackToplevelHelper.qml
- src/treeland/foreigntoplevelmanagerv1.cpp
- src/treeland/foreigntoplevelmanagerv1.h
- src/treeland/helper.cpp
> fix: not responding to client requests on foreigntoplevel

- src/treeland/quick/qml/Main.qml
Fix input popup surface item not removed due to wrong property name.
Log: fix input popup surface item not removed
> fix: input popup surface item not removed

- src/treeland/quick/qml/StackWorkspace.qml
- src/treeland/quick/qml/XdgSurface.qml
1. don't change initial position of popup
2. parent of popup should be parentItem.item, shell(Popup type) is not QQuickItem
3. check popup position do not exceed the screen display area
https://github.com/vioken/waylib/pull/241
> fix: position of popup component

- src/treeland/quick/qml/Main.qml
- src/treeland/quick/qml/StackWorkspace.qml
- src/treeland/quick/qml/TiledWorkspace.qml
- src/treeland/quick/qml/XdgSurface.qml
https://github.com/vioken/waylib/pull/246
> Fix can't drag surface to other output

- debian/rules
use debian default libexec dir
Log:
> chore: remove special libexec dir

- src/treeland/data/treeland-foreign-toplevel-manager-v1.xml
- src/treeland/protocols/CMakeLists.txt
- src/treeland/protocols/dockpreviewcontextv1.cpp
- src/treeland/protocols/foreign_toplevel_manager_impl.cpp
- src/treeland/protocols/foreign_toplevel_manager_impl.h
- src/treeland/protocols/foreigntoplevelhandlev1.cpp
- src/treeland/protocols/foreigntoplevelhandlev1.h
- src/treeland/protocols/foreigntoplevelmanagerv1.cpp
- src/treeland/quick/protocols/foreigntoplevelmanagerv1.cpp
- src/treeland/quick/protocols/foreigntoplevelmanagerv1.h
- src/treeland/quick/qml/CMakeLists.txt
- src/treeland/quick/qml/CloseAnimation.qml
- src/treeland/quick/qml/DockPreview.qml
- src/treeland/quick/qml/LayerSurface.qml
- src/treeland/quick/qml/StackToplevelHelper.qml
- src/treeland/quick/qml/StackWorkspace.qml
- src/treeland/quick/utils/CMakeLists.txt
- src/treeland/quick/utils/dockpreviewfilter.cpp
- src/treeland/quick/utils/dockpreviewfilter.h
依赖 https://github.com/vioken/waylib/pull/250
> support dock preview

- src/treeland/quick/protocols/foreigntoplevelmanagerv1.cpp
send wrong identifier. why two xdgsurface of one program has the same wlr_xdg_surface resource.
Issue: https://github.com/linuxdeepin/developer-center/issues/6885
Log:
> fix: dock crash

- src/greeter/CMakeLists.txt
- src/treeland/quick/protocols/CMakeLists.txt
- src/treeland/quick/qml/CMakeLists.txt
- src/treeland/quick/utils/CMakeLists.txt
log: cmake Warning: The greeterplugin target is a QML module with target path TreeLand/Greeter.
It uses an OUTPUT_DIRECTORY of build/src/greeter, which should end in the same
target path, but doesn't.  Tooling such as qmllint may not work correctly.
> chore: uses an OUTPUT_DIRECTORY end in the same target path

- src/treeland/quick/qml/CMakeLists.txt
- src/treeland/quick/qml/StackWorkspace.qml
- src/treeland/quick/qml/WindowDecoration.qml
以后再尝试直接在surfaceitem上裁剪，本次只临时处理一次标题栏的按钮
> refactor: use DTK WindowButton

- src/treeland/quick/qml/LayerSurface.qml
- src/treeland/quick/qml/StackToplevelHelper.qml
log: client will unmap before destory, pendingDestroy not set if don't wait CloseAnimation
> Fix: not destroyObject when not show closeAnimation

- .envrc
- flake.nix
- nix/default.nix
> chore: fix not found qtsvg in nixos

- src/treeland/quick/qml/Main.qml
log: After a screen is pulled out, the cursor will automatically return to other screens and trigger the LastActiveCursorItemChanged signal. However, if the cursor is on two screens at the same time before the screen is pulled out and has not left the previous screen, the signal will not be triggered.
> fix: greeter maybe not show when screen was pulled out

- src/treeland/quick/qml/WindowDecoration.qml
Currently clicking on ssd titlebar won't activate the surface.
Activate surface via setting Helper.activatedSurface, when titlebar or edge region clicked
> fix: activate wrapped surface when SSD clicked

- src/treeland/quick/qml/CMakeLists.txt
- src/treeland/quick/qml/EQHGrid.qml
- src/treeland/quick/qml/Main.qml
- src/treeland/quick/qml/StackWorkspace.qml
- src/treeland/quick/qml/WindowsSwitcher.qml
features include:
- indicator
- win11-like equal-height-grid layout of window thumbnails
- indicator follows screen not whole virtual desktop scene
- tap & scroll interaction of the indicator
- current window preview
- opaque not-focused windows
- fix the bug that windows still receiving input when switcher shows
> feat: beter Alt+Tab window switcher

- src/treeland/quick/qml/WindowsSwitcher.qml
Referring to kwin/mutter standard behavior, shoudn't actually activate win when previewing / in switching.
> Fix winpreview activate bahavior

- src/treeland/quick/qml/Main.qml
- src/treeland/quick/qml/QmlHelper.qml
- src/treeland/quick/qml/StackWorkspace.qml
- src/treeland/quick/qml/WindowsSwitcher.qml
- src/treeland/quick/utils/helper.cpp
- src/treeland/quick/utils/helper.h
- Sync state between qml and C++. Now C++ only provides keyboard navigation events, state is maintained in qml.
- Using qml `ShortCut` type for trigger/toggle based shortcuts like multitaskview `Meta+S`, screenlock `Meta+L`.
suggests https://github.com/vioken/waylib/pull/287 for auto-repeat
> Refactor shortcuts of winswitcher and one-shot kinds like multitaskview

- src/treeland/quick/qml/StackToplevelHelper.qml
if surface mapped when not visible, it will only change mode to sizefromsurf, but not applied, so has zero size
> fix: trigger resize on mode change

- src/treeland/quick/qml/WindowDecoration.qml
layer.effect creates a sibling node and set hideSource to true, results in both sibling and origin invisible in shadereffectsource when they're not effectiveVisible
(maybe a bug involving hideSource, if set only one shadereffectsource can display)
so use opacity=0 & explicit mask effect item to avoid.
> Fix: ssd's clipped content invisible in shadereffectsource when sourceitem not visible

- src/treeland/quick/qml/Main.qml
activated surface may lose focus in qt when other view is on, so use activatedsurface to check
> Fix: keyboardfocus should not follow activeItem

- src/greeter/Center.qml
- src/greeter/Greeter.qml
- src/greeter/UserInput.qml
- src/treeland/quick/qml/LayerSurface.qml
- src/treeland/quick/qml/Main.qml
- src/treeland/quick/qml/MultitaskView.qml
- src/treeland/quick/qml/StackToplevelHelper.qml
- src/treeland/quick/qml/StackWorkspace.qml
- src/treeland/quick/qml/ToplevelContainer.qml
- src/treeland/quick/qml/WindowDecoration.qml
- when current activated is minimize / closed
- when active workspace is changed
- https://github.com/linuxdeepin/treeland/pull/180 is merged to this
> Reduce use of `forceActiveFocus`, use focusscope etc. to automatically pass focus along the item tree. Currently uses of `forceActiveFocus` lacks checking, may result in:
> 
> * passwordinput failed to get focus, but unset workspace's focus so focus is set to root content item
> * greeter shows but later some surface becomes mapped so focus is robbed
> 
> Also fix that focus get lost when only there's one surface after switcher or some treeland controls get focus
> 
> based on [vioken/waylib#285](https://github.com/vioken/waylib/pull/285)
> Feat activated surface auto transition

- src/treeland/quick/qml/Main.qml
- src/treeland/quick/qml/StackWorkspace.qml
Input popup is missing due to the introduce of workspace
it's created following keyboardfocus,
when surface moved between workspaces, it follows.
> Fix: create inputpopup out of workspace

- src/treeland/quick/qml/QmlHelper.qml
- src/treeland/quick/qml/StackWorkspace.qml
- src/treeland/quick/qml/TiledWorkspace.qml
This reverts commit 416a78c8859e4ae1c1fc5dc8de6565e37e0055ad.
> Revert "chore: move getSurfaceItemFromWaylandSurface to QmlHelper"

- src/treeland/quick/qml/Main.qml
when there is no drm, the cursor is the native
Xorg or Wayland compositor rendering display.
Log: fixed rendering one more cursor
Issue: https://github.com/linuxdeepin/treeland/issues/265
> fix: cursor display abnormality

- src/treeland/quick/qml/Main.qml
set seat's keyboard focuswin on renderwindow initialize, so that keyevent can be received even if no mousemove happens
> Fix initialize focuswin

- src/treeland/quick/qml/StackToplevelHelper.qml
- src/treeland/quick/utils/helper.cpp
fix https://github.com/linuxdeepin/treeland/issues/183.
otherwise contentItem will change size before client committed so stretch.
depends on https://github.com/vioken/waylib/pull/308
> Fix: use sizeFromSurface & resizeBySurface when drag resizing

- src/qml/Main.qml
- src/qml/QmlHelper.qml
- src/qml/StackWorkspace.qml
- src/qml/WindowDecoration.qml
- src/utils/helper.h
-  initial win pos
- follow cursor's output
- policies
- start from cursor pos, stacking following down-right line
- center then scatter at corners
> Feat: spawning window layout rule

- src/qml/QmlHelper.qml
- src/qml/StackToplevelHelper.qml
- src/qml/StackWorkspace.qml
- src/qml/SurfaceWrapper.qml
Impl basic winlayout restore on output changes.
- outputs environment
- use the set of outputs as hash-key
- state restore
- only restore the surfaces that has a matched state
- use intermediate state for transition animating
> Winlayout restore on output changes

- src/qml/StackWorkspace.qml
Desktop and Launchpad do not yet support LayerShell
Log:
> chore: Remove the decorator of a part of the program

- src/modules/primary-output/impl/output_manager_impl.cpp
- src/modules/window-management/impl/window_management_impl.cpp
The failure of wl_resource_set_implementation to destroy results in a request crash on the client.
> fix: Show desktop crash

- src/modules/foreign-toplevel/foreigntoplevelmanagerv1.cpp
- src/modules/foreign-toplevel/foreigntoplevelmanagerv1.h
- src/modules/foreign-toplevel/impl/foreign_toplevel_manager_impl.h
- src/modules/personalization/personalizationmanager.cpp
- src/modules/personalization/personalizationmanager.h
- src/qml/DockPreview.qml
- src/qml/Main.qml
- src/qml/StackToplevelHelper.qml
- src/qml/StackWorkspace.qml
- src/qml/SurfaceWrapper.qml
- src/qml/ToplevelContainer.qml
- src/utils/helper.cpp
- src/utils/helper.h
Actively move the activation state of the window that is about to be closed
Log:
> fix: Crash when window flashes

- src/qml/Main.qml
- src/qml/StackWorkspace.qml
- src/utils/helper.cpp
The focus can only be updated between the upper and lower levels, but the layershell is not managed by the workspace, so we need to manually update the status.
When using qml popup, the focus will return to the root window and need to be manually updated to the workspace.
Log:
> fix: item focus not auto select

- src/core/qml/DockPreview.qml
Log: shouldn't set elide for tooltip, and I forgot why I didn't use AlignHCenter before, but now it works fine Only update the transparency of tooltipText/titleIconText, no longer modify visible, to prevent both from being invisible when the state is wrong
> fix: the tooltip text may disappear unexpectedly

- debian/treeland.install
- misc/systemd/treeland.service.in
- src/CMakeLists.txt
- src/main.cpp
- src/treeland.sh
- src/utils/cmdline.cpp
- src/utils/cmdline.h
This is a workaround.
On the VirtualBox no 3D accelerate, eglInitialize will crash.
Depends https://github.com/vioken/waylib/pull/615
> Fix can't start on VirtualBox

- src/seat/helper.cpp
Log: OutputViewport are anchor to it's parent, should setX/Y for it's parent
> fix: can't set output's postion

- src/core/shellhandler.cpp
Log: When the parent of the container is different, the z-axis cannot be compared and we need to look up to find the common ancestor
> fix: layer shell's popup not enter popup container

- src/core/treeland.cpp
Log: ddm is started as user dde and cannot access other users' home directories
Fix: https://github.com/linuxdeepin/treeland/issues/388
> fix: can't load plugin in debug build

- waylib/src/server/kernel/private/wsurface_p.h
- waylib/src/server/kernel/woutput.cpp
- waylib/src/server/kernel/woutput.h
- waylib/src/server/kernel/wsurface.cpp
- waylib/src/server/kernel/wsurface.h
- waylib/src/server/qtquick/woutputhelper.cpp
- waylib/src/server/qtquick/woutputhelper.h
- waylib/src/server/qtquick/woutputrenderwindow.cpp
- waylib/src/server/qtquick/woutputrenderwindow.h
- waylib/src/server/qtquick/wsurfaceitem.cpp
1.  The previous logic only redrew the surface when the buffer changed, which is insufficient.
2.  Firefox frequently updates the frame callback list using `WLR_SURFACE_STATE_FRAME_CALLBACK_LIST`. Receiving such commits should also trigger a redraw to trigger the frame done event for the surface.
3.  This fixes an issue where Firefox windows would often not refresh until the mouse was moved.
Influence:
1. Verify that Firefox windows now refresh correctly without requiring mouse movement.
2. Ensure that other applications are not negatively affected by this change.
3. Check for any performance regressions related to the increased redraw frequency.
fix: 当帧回调列表更新时重绘
1. 之前的逻辑仅在缓冲区更改时才重绘表面，这不足够。
2. Firefox 经常使用 `WLR_SURFACE_STATE_FRAME_CALLBACK_LIST` 更新帧回调列 表。收到此类提交也应触发重绘，以触发表面的帧完成事件。
3. 这修复了 …
> fix: redraw when frame callback list updates
