linuxdeepin/treeland

.envrc, .gitignore, CMakeLists.txt, flake.lock, flake.nix, nix/default.nix, src/treeland/CMakeLists.txt, src/treeland/treeland-fake-session/CMakeLists.txt, src/treeland/treeland-helper/CMakeLists.txt
Need: https://github.com/vioken/waylib/pull/203
=> Support nix build and better cmake

src/treeland/Main.qml
ForeignToplevel cannot handle popup window
Log:
=> fix: crash when popup window show

flake.lock, src/treeland/StackWorkspace.qml, src/treeland/TiledWorkspace.qml
https://github.com/vioken/waylib/pull/207
=> Make layer surface support popup

src/treeland/CMakeLists.txt, src/treeland/InputPopupSurface.qml, src/treeland/Main.qml, src/treeland/QmlHelper.qml, src/treeland/StackWorkspace.qml, src/treeland/TiledWorkspace.qml
Add input method support from waylib.
Log: add input method support
=> feat: add input method support

src/treeland/InputPopupSurface.qml, src/treeland/Main.qml, src/treeland/StackWorkspace.qml, src/treeland/TiledWorkspace.qml
Optimize position of input popup surface.
Log: optimize input popup surface
=> refactor: optimize input popup surface

src/treeland/StackWorkspace.qml
change enable to serverDecorationEnabled
Log:
=> fix: decoration not working

src/treeland/foreigntoplevelmanagerv1.cpp
only send title appid pid and identifier
Log:
=> fix: wrong signal sent

CMakeLists.txt, debian/control, src/greeter/CMakeLists.txt, src/greeter/Center.qml, src/greeter/Greeter.qml, src/greeter/GreeterModel.qml, src/greeter/RoundBlur.qml, src/greeter/UserInput.qml, src/greeter/UserList.qml, src/greeter/UserModel.cpp, src/greeter/UserModel.h, src/helper/singlewaylandhelper.cpp
=> feat: impl userList

.obs/workflows.yml, .reuse/dep5, flake.lock, flake.nix, nix/default.nix
log: update flake and use dtk6
=> feat: fix nix build and remove debian ci

flake.lock, flake.nix, nix/default.nix
log: update flake and fix patch for nix
=> fix: fix nix build ci and devShell

src/treeland/data/CMakeLists.txt, src/treeland/data/treeland-personalization-manager-v1.xml, src/treeland/protocols/CMakeLists.txt, src/treeland/protocols/personalization_manager_impl.cpp, src/treeland/protocols/personalization_manager_impl.h, src/treeland/protocols/personalizationmanager.cpp, src/treeland/protocols/personalizationmanager.h, src/treeland/protocols/personalizationwindowcontext.cpp, src/treeland/quick/protocols/CMakeLists.txt, src/treeland/quick/protocols/qwpersonalizationmanager.cpp, src/treeland/quick/protocols/qwpersonalizationmanager.h, src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/treeland-fake-session/CMakeLists.txt, src/treeland/treeland-fake-session/fake-session.cpp, src/treeland/treeland-fake-session/fake-session.h
=> feat: add wallpaper protocol

.reuse/dep5, renovate.json
=> feat: automate nix updates with renovate

src/treeland/quick/qml/StackWorkspace.qml
=> fix: decoration not show

src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/qml/TiledToplevelHelper.qml, src/treeland/quick/qml/XdgSurface.qml
=> fix: window state not working

data/wayland-sessions/treeland.desktop.in, src/treeland/treeland-fake-session/fake-session.cpp
use DDE as XDG_CURRENT_DESKTOP
Log:
=> fix: XDG_CURRENT_DESKTOP is wrong

.gitignore, src/treeland/CMakeLists.txt, src/treeland/data/treeland-personalization-manager-v1.xml, src/treeland/protocols/CMakeLists.txt, src/treeland/protocols/personalization_manager_impl.cpp, src/treeland/protocols/personalization_manager_impl.h, src/treeland/protocols/personalizationmanager.cpp, src/treeland/protocols/personalizationmanager.h, src/treeland/protocols/personalizationwallpapercontext.cpp, src/treeland/quick/protocols/qwpersonalizationmanager.cpp, src/treeland/quick/protocols/qwpersonalizationmanager.h, src/treeland/quick/qml/OutputDelegate.qml, src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/treeland-fake-session/fake-session.cpp, src/treeland/treeland-fake-session/fake-session.h, src/treeland/treeland-wallpaper/CMakeLists.txt, src/treeland/treeland-wallpaper/PropertyItemDelegate.qml, src/treeland/treeland-wallpaper/Wallpaper.qml, src/treeland/treeland-wallpaper/main.cpp, src/treeland/treeland-wallpaper/main.qml, src/treeland/treeland-wallpaper/personalizationmangerclient.cpp, src/treeland/treeland-wallpaper/personalizationmangerclient.h
Log: added interface to set wallpaper
=> feat: added interface to set wallpaper

debian/changelog
=> chore: release 0.1.1

src/daemon/Display.cpp
some application need check current compositer, so We have this.
Log:
=> feat: add DDE_CURRENT_COMPOSITER environment

flake.lock, flake.nix, nix/default.nix
=> fix: build on nix ci

src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/OutputDelegate.qml
Log: sync https://github.com/vioken/waylib/pull/248
=> Fix wlr output manager get wrong position

CMakeLists.txt, data/shortcuts/_deepin-screen-recorder.ini, data/shortcuts/_deepin-screenshot.ini, src/treeland/protocols/qshortcutmanager.cpp, src/treeland/protocols/shortcut_manager_impl.cpp, src/treeland/protocols/shortcut_manager_impl.h, src/treeland/quick/protocols/shortcutmanager.cpp, src/treeland/treeland-fake-session/fake-session.cpp, src/treeland/treeland-fake-session/fake-session.h
TODO: convert to new config
Log:
=> chore: support old dde custom shortcut

src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/OutputDelegate.qml
log: sync https://github.com/vioken/waylib/pull/256
=> fix: crash when remove outputs

src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/OutputDelegate.qml
sync from waylib 0574fff261b06bdf80fc18639b38a1343ba23ee1
Log:
=> fix: fix magnifying glass on multi outputs

src/greeter/Greeter.qml, src/treeland/quick/qml/Main.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/6611
=> fix: greeter not show in active output

src/treeland/quick/utils/helper.cpp, src/treeland/treeland-wallpaper/personalizationmangerclient.cpp
=> fix: typo and suppress warnings

src/treeland/quick/qml/OutputDelegate.qml
sync: https://github.com/vioken/waylib/pull/262
=> fix: dragIcon not show when use hardware cursor

src/treeland/quick/qml/WindowDecoration.qml
Button item will take focus and not back.
Log:
=> fix: window lost focus

src/treeland/quick/protocols/qwpersonalizationmanager.cpp, src/treeland/treeland-fake-session/fake-session.cpp, src/treeland/treeland-wallpaper/Wallpaper.qml, src/treeland/treeland-wallpaper/wallpapercardmodel.cpp
Log: start deepin input method and application manager
=> feat: start deepin input method and application manager

src/treeland/quick/qml/Main.qml
Previous change: https://github.com/linuxdeepin/treeland/pull/102
=> fix: greeter maybe not change when cursor in muitoutput

src/treeland/protocols/shortcut_manager_impl.cpp
not insert resource to wl_list
Log:
=> fix: shortcut manager will crash

src/treeland/CMakeLists.txt, src/treeland/InWindowBlur.qml, src/treeland/override_dtkdeclarative_qml.qrc, src/treeland/treeland.cpp
it exists some bug in treeland, so we override dtkdeclarative's
blur.
It depends on https://github.com/linuxdeepin/dtkdeclarative/pull/274
=> feat: override dtk's blur

src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/qml/TiledWorkspace.qml, src/treeland/quick/utils/helper.cpp
Part of https://github.com/vioken/waylib/pull/265
=> fix: can not click popup menu

src/helper/HelperApp.cpp, src/helper/UserSession.cpp, src/treeland/treeland-fake-session/fake-session.cpp
https://github.com/linuxdeepin/developer-center/issues/6595
=> fix: prevent treeland exit by ctrl+c

src/treeland/quick/qml/Main.qml
sync: https://github.com/vioken/waylib/pull/258
=> fix: renderWindow's size not follow outputDelegate to change

src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/quick/qml/StackWorkspace.qml
sync: https://github.com/vioken/waylib/pull/263
=> fix: not react fullscreen request

src/treeland/treeland-wallpaper/CMakeLists.txt, src/treeland/treeland-wallpaper/Wallpaper.qml, src/treeland/treeland-wallpaper/WallpaperSetting.qml, src/treeland/treeland-wallpaper/personalizationmangerclient.cpp, src/treeland/treeland-wallpaper/translations/wallpaper.en_US.ts, src/treeland/treeland-wallpaper/translations/wallpaper.zh_CN.ts
Log: add translation for wallpaper
=> chore: add translation for wallpaper

src/treeland/quick/qml/StackWorkspace.qml
sync: https://github.com/vioken/waylib/pull/264
=> fix: fullscreen surface should over layershell

src/treeland/quick/qml/StackToplevelHelper.qml
log: output.topMargin has removed
=> fix: fullscreen and maximize get wrong size

src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/quick/qml/StackWorkspace.qml
dde-desktop need lower all window.
dde-launchpad need upper all window but lower dock.
Log:
=> chore: special some window

src/treeland/quick/qml/DockPreview.qml, src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/quick/utils/dockpreviewfilter.cpp, src/treeland/quick/utils/dockpreviewfilter.h, src/treeland/quick/utils/treelandhelper.cpp, src/treeland/quick/utils/treelandhelper.h
=> fix: cannot close window on decoration

src/treeland/quick/qml/StackToplevelHelper.qml
log: we use TreeLandHelper in Treeland
=> fix: can't get layershell exclusive zone size

src/daemon/Display.cpp
DDE_CURRENT_COMPOSITER => DDE_CURRENT_COMPOSITOR
need change dde-desktop and dde-shell.
Log:
=> fix: typo compositor

data/systemd/CMakeLists.txt, data/systemd/dde-fake-session-initialized.target.wants/fake-dde-osd.service, src/treeland/treeland-fake-session/fake-session.cpp
run dde-osd before dde-shell.
Log:
=> chore: add fake dde-osd startup

src/treeland/quick/qml/StackWorkspace.qml
force launchpad show on bottom of dock
Log:
=> fix: dde-launchpad will clip dock

src/helper/Backend.h, src/helper/HelperApp.cpp
only greeter can handle sigterm
Log:
=> fix: systemd restart will crash

data/systemd/CMakeLists.txt, data/systemd/dde-fake-session-shutdown.target, data/systemd/dde-fake-session.service.in, data/systemd/dde-fake-session.target, src/treeland/treeland-fake-session/fake-session.cpp, src/treeland/treeland-fake-session/fake-session.h
add dde-fake-session-shutdown.target
Log:
=> chore: add systemd service

src/treeland/quick/qml/LayerSurface.qml
log: when should set visible for root item
=> fix: layershell not hide when unmapped

src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/utils/helper.cpp, src/treeland/quick/utils/treelandhelper.cpp, src/treeland/treeland-wallpaper/main.qml
skip dde-desktop and dde-launchpad
TODO: move to a rules class.
Log:
=> fix: cannot switch window

src/treeland/quick/qml/LayerSurface.qml, src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/qml/TiledWorkspace.qml
=> fix: click menu will crash

data/systemd/CMakeLists.txt, data/systemd/dde-fake-session-initialized.target.wants/fake-dde-filemanager-server.service
Issue: 
- https://github.com/linuxdeepin/developer-center/issues/6891
- https://github.com/linuxdeepin/developer-center/issues/7017
=> chore: add fake-dde-filemanager-server.service

src/treeland/quick/protocols/qwpersonalizationmanager.cpp, src/treeland/quick/qml/Main.qml, src/treeland/treeland.cpp, src/treeland/treeland.h
=> fix: cannot set wallpaper

data/systemd/CMakeLists.txt
=> fix: install symlink

data/systemd/CMakeLists.txt, debian/changelog
=> chore: release 0.2.1

src/greeter/UserModel.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/7105
=> fix: greeter should refresh after add/del user

debian/changelog
=> chore: release 0.2.2

.reuse/dep5, flake.lock, flake.nix, garnix.yaml, nix/default.nix, src/treeland/quick/qml/CMakeLists.txt
log: use `nix run -v -L .#qemu` to test
=> feat: allow ddm works in nixos

.editorconfig, .reuse/dep5, src/treeland/protocols/ext_foreign_toplevel_list_impl.cpp, src/treeland/protocols/personalization_manager_impl.cpp, src/treeland/protocols/shortcut_manager_impl.cpp, src/treeland/quick/protocols/shortcutmanager.cpp, src/treeland/quick/protocols/shortcutmanager.h, src/treeland/quick/qml/WindowDecoration.qml, src/treeland/quick/utils/helper.h, src/treeland/treeland-fake-session/fake-session.cpp, src/treeland/treeland-wallpaper/wallpapercardmodel.cpp, src/treeland/treeland-wallpaper/wallpapercardmodel.h
=> chore: remove compiler warning

CMakeLists.txt, src/common/Session.cpp, src/common/ThemeConfig.cpp, src/helper/UserSession.cpp, src/helper/UserSession.h, src/treeland/CMakeLists.txt, src/treeland/quick/qml/CMakeLists.txt, src/treeland/treeland.cpp
Log: waylib need qt >= 6.6 anyway
=> chore: remove support for qt < 6.6

src/treeland/quick/qml/CMakeLists.txt, src/treeland/quick/qml/MultitaskView.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/utils/helper.cpp, src/treeland/quick/utils/helper.h
Using unscrollable equal-height-grid layout, support mouse interaction, no keyboard interaction.
Place to each output.
=> Feat: impl basic multitaskview

src/treeland/quick/qml/LayerSurface.qml
Currently it's anchored to whole virtual desktop.
Use outputCoordMapper to create sibling item to be anchored to. The output anchored to can be passed in or default as `primaryOutput()`
=> Feat: anchor layershell to output

src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/qml/WindowDecoration.qml
hard to find, largely owing to https://github.com/vioken/waylib/pull/294
Also fix windecoration's prop type
=> fix: xwayland no display

src/treeland/quick/qml/LayerSurface.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/utils/helper.h
- fix margins uninitialized bug
- support layersurface's output prop
- if no output, use activeoutput to initialize; output remove unmanaged
- depends https://github.com/vioken/waylib/pull/296
=> Fix dde shell no display

src/treeland/quick/qml/StackWorkspace.qml
log: sync https://github.com/vioken/waylib/pull/273
=> chore: update z value for WindowDecoration

src/treeland/quick/qml/LayerSurface.qml
log: need https://github.com/vioken/waylib/pull/297
=> chore: the property change should be atomic

src/treeland/quick/qml/CMakeLists.txt, src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/NewAnimation.qml, src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/quick/qml/StackWorkspace.qml
This function is for demonstration purposes only, and there is still work to be done.
Log: 支持新窗口动画
=> feat: add new window animation

data/interfaces/org.freedesktop.login1.Seat.xml, data/interfaces/org.freedesktop.login1.User.xml, src/greeter/CMakeLists.txt, src/treeland/treeland-wallpaper/CMakeLists.txt
as title
Close: https://github.com/linuxdeepin/treeland/pull/210
Log:
=> fix: support qt 6.7

src/treeland/data/CMakeLists.txt, src/treeland/treeland-fake-session/CMakeLists.txt, src/treeland/treeland-helper/CMakeLists.txt
log: just use pkgconfig to find
=> fix: not link wayland-client in opensuse

src/treeland/quick/qml/Main.qml, src/treeland/quick/utils/helper.cpp, src/treeland/quick/utils/helper.h
cherry-pick waylib f5a380364608c99ce8eab7ca5c24d344a49137ae
Log:
=> chore: don't auto enable output

src/treeland/quick/qml/EQHGrid.qml, src/treeland/quick/qml/MultitaskView.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/qml/WindowsSwitcher.qml, src/treeland/quick/utils/filterproxymodel.cpp, src/treeland/quick/utils/filterproxymodel.h
- add per output workspace listview
- dynamic update with current workspace
- drag surface to workspace interaction & animation
- multitaskview & winswitcher dynamic layout
=> Feat: introduce multiworkspace interactions to multitaskview

src/treeland/treeland.cpp
=> chore: don't check ret != 0 twice

src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/qml/WindowDecoration.qml, src/treeland/quick/utils/helper.cpp
Log: better for touch screen
need https://github.com/vioken/waylib/pull/315
=> chore: fix window decoration in touchscreen

src/treeland/quick/qml/LayerSurface.qml
log: should not closed layersurface when leave output, it maybe temporary
=> fix: layer surface crash in muitoutput

src/treeland/quick/qml/StackWorkspace.qml
change to output center
Closed: https://github.com/linuxdeepin/treeland/issues/232
Log: 默认窗口出现在屏幕中间
=> feat: window default position

src/greeter/Greeter.qml, src/treeland/quick/qml/Main.qml
=> fix: greeter not lazyload

data/systemd/CMakeLists.txt, data/systemd/dde-session-pre.target.wants/treeland-sd.service.in, data/systemd/dde-session-pre.target.wants/treeland-sd.socket, data/systemd/dde-session-pre.target.wants/treeland.service.in, data/wayland-sessions/treeland-user.desktop.in, src/treeland/systemd-socket.cpp, src/treeland/treeland.cpp
- **feat: default usage dtk log system**
- **fix: layer surface crash in muitoutput**
- **feat: window default position**
- **chore: remove socket manager**
- **feat: support crash reboot**
- **chore: lazy load greeter module**
- **fix: greeter not lazyload**
- **feat: add user level treeland service**
=> Support run treeland on user level

src/treeland/quick/qml/EQHGrid.qml, src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/MultitaskView.qml, src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/quick/qml/StackWorkspace.qml
- support drag to reorder
- add / remove button
- fix enter animation
=> Improve workspace list interactions & animations in multitaskview 

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
=> chore: add issue template

src/treeland/quick/qml/Main.qml
missing FractionalScaleManagerV1 create
log: support wayland window fraction scale
=> feat: add FractionalScaleManagerV1 registration

src/treeland/quick/qml/DockPreview.qml, src/treeland/quick/qml/QmlHelper.qml, src/treeland/quick/qml/StackWorkspace.qml, src/treeland/quick/qml/TiledWorkspace.qml
=> chore: move getSurfaceItemFromWaylandSurface to QmlHelper

src/treeland/quick/qml/Main.qml
log: need https://github.com/vioken/waylib/pull/341
=> feat: add support for screen copy

flake.nix, src/treeland/quick/qml/Main.qml, src/treeland/quick/qml/StackWorkspace.qml
=> fix: xwayland item can't get input

CMakeLists.txt
log: just use "-DADDRESS_SANITIZER=ON" for better debug
=> feat: add Asan cmake option

src/CMakeLists.txt, src/greeter/CMakeLists.txt, src/treeland/quick/qml/StackToplevelHelper.qml, src/treeland/treeland-wallpaper/CMakeLists.txt
=> fix: set correct QML_IMPORT_PATH

src/qml/StackWorkspace.qml, src/qml/ToplevelContainer.qml
remove duplicate TreeLand.Protocols imports.
Log:
=> fix: remove duplicate imports

src/modules/treeland-output-management/impl/output_manager_impl.cpp, src/modules/treeland-output-management/impl/output_manager_impl.h, src/modules/treeland-output-management/outputmanagement.cpp, src/modules/treeland-output-management/outputmanagement.h
Log: fix build in new qwlroots/waylib
=> fix: don't use qwobject in treeland-output-management

src/qml/Main.qml, src/qml/OutputDelegate.qml
Fix: https://github.com/linuxdeepin/treeland/issues/171
Log:
=> fix: Multi screen crash on startup

CMakeLists.txt, tests/CMakeLists.txt, tests/test_window_bg/CMakeLists.txt, tests/test_window_bg/main.cpp
=> feat: add window background test demo

data/dbus/org.deepin.compositor1.xml, data/systemd/CMakeLists.txt, data/systemd/dde-session-pre.target.wants/treeland-sd.service.in, data/systemd/dde-session-pre.target.wants/treeland-xwayland.service.in, data/systemd/dde-session-pre.target.wants/treeland-xwayland.socket, data/systemd/dde-session-pre.target.wants/treeland.service.in, src/qml/Main.qml, src/systemd-socket.cpp, src/treeland.cpp, src/treeland.h, src/utils/helper.cpp, src/utils/helper.h
=> chore: support xwayland socket

data/systemd/CMakeLists.txt, data/systemd/dde-session-pre.target.wants/treeland-sd.service.in, data/systemd/dde-session-pre.target.wants/treeland-shortcut.service.in, src/CMakeLists.txt, src/treeland-shortcut/CMakeLists.txt, src/treeland-shortcut/shortcut.cpp, src/treeland-shortcut/shortcut.h, src/treeland-shortcut/shortcuts/_dde-launchpad.ini, src/treeland-shortcut/shortcuts/_deepin-screen-recorder.ini, src/treeland-shortcut/shortcuts/_deepin-screenshot.ini, src/treeland-shortcut/shortcuts/_deepin-terminal.ini, src/treeland.cpp
DDE team don't have time to support it.
=> chore: add shortcut client

flake.lock, src/modules/ext-foreign-toplevel-list/extforeigntoplevellist.cpp, src/modules/ext-foreign-toplevel-list/extforeigntoplevellist.h, src/modules/treeland-foreign-toplevel/foreigntoplevelmanagerv1.cpp, src/modules/treeland-foreign-toplevel/foreigntoplevelmanagerv1.h, src/modules/treeland-output-management/outputmanagement.cpp, src/modules/treeland-output-management/outputmanagement.h, src/modules/treeland-personalization-manager/personalizationmanager.cpp, src/modules/treeland-personalization-manager/personalizationmanager.h, src/modules/treeland-shortcut-manager/shortcutmanager.cpp, src/modules/treeland-shortcut-manager/shortcutmanager.h, src/qml/Main.qml, src/qml/OutputDelegate.qml, src/utils/helper.cpp, src/utils/surfaceitemfactory.cpp
log:
- https://github.com/vioken/waylib/pull/377 Override xdg output manager protocol for the XWayland clients
- https://github.com/vioken/waylib/pull/372 Supports filter wl_global by wl_client
- https://github.com/vioken/waylib/pull/374 Xwayland and Wayland synchronized scaling
- https://github.com/vioken/waylib/pull/379 OutputViewport: Add input property
need:
- https://github.com/vioken/waylib/pull/380
close: https://github.com/linuxdeepin/treeland/issues/305
=> chore: sync missing change in waylib 

src/qml/LayerSurface.qml
update LayerShell property
Log:
=> fix: layershell surface -> shellSurface

src/modules/treeland-personalization-manager/personalizationmanager.cpp
log: fix wallpaper not work in lightdm
=> fix: set uid by self when not use ddm

src/modules/treeland-personalization-manager/personalizationmanager.cpp, src/modules/treeland-personalization-manager/personalizationmanager.h, src/qml/Main.qml, src/qml/StackWorkspace.qml
=> fix(outputDelegate): cannot read default wallpaper

src/modules/window-management/windowmanagement.cpp
Update Desktp State when a client sends a request
=> fix: Adaptive waylib reconstruction

src/treeland-wallpaper/Wallpaper.qml
Flickable need width and height
Log:
=> fix: wallpaper client not show picture

src/utils/helper.cpp
=> fix: xwayland dbus not return display name

src/utils/helper.cpp
=> chore: change shortcut handle from keypress to keyrelease

tests/test_window_crusor/CMakeLists.txt
=> fix(tests): connot find persionalmanager xml

src/treeland-wallpaper/Wallpaper.qml
=> fix: wallpaper clients not show picture

src/modules/window-management/impl/window_management_impl.cpp, src/modules/window-management/protocols/treeland-window-management-v1.xml, src/modules/window-management/windowmanagement.cpp, tests/test_show_desktop/main.cpp
=> fix: Remove the treeland field from the protocol file interface

src/utils/helper.cpp
=> fix: output not remove

src/qml/StackWorkspace.qml, src/qml/TiledWorkspace.qml
=> fix: err position for muliti-level menu

debian/changelog
=> chore: release 0.2.3

LICENSES/LicenseRef-Qt-Commercial.txt, src/modules/dde-shell/ddeshellattached.cpp, src/utils/loginddbustypes.cpp, src/utils/loginddbustypes.h
=> chore: add missing license

src/seat/helper.cpp
Log: Record screen configuration information and restore the configuration at next startup
=> feat: cache outputs settings

debian/changelog
=> chore(debian): bump version to 0.5.18

src/seat/helper.cpp, src/seat/helper.h
Log: protocols used for idle behavior such as screen blanking, locking, and screensaving
=> feat: support idlenotify idleinhibit and outputpowermanagement

debian/changelog
=> chore(debian): bump version to 0.5.19

src/modules/personalization/personalizationmanager.cpp, src/seat/helper.cpp
close: https://github.com/linuxdeepin/treeland/issues/383
=> chore: move all QSettings config to AppConfigLocation

waylib/src/server/kernel/wsocket.cpp
1. Set server socket to non-blocking mode to prevent accept() calls from blocking the main thread indefinitely.
2. Improved wl_os_accept_cloexec function to use accept4 with SOCK_CLOEXEC flag as the preferred method on modern Linux systems, with fallback to traditional accept() + fcntl approach for compatibility.
3. Added proper error handling for ENOSYS case when accept4 is not supported.
The blocking issue occurred when the Wayland server was waiting for client connections, causing the entire compositor to freeze. This fix follows the same pattern used in libwayland for robust socket handling.
Log: Fixed Wayland server socket blocking in accept() calls
Influence:
1. Test server startup and client connection establishment
2. Verify proper handling of multiple concurrent client …
=> fix: Fix socket blocking issue in Wayland server connection handling
